version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]
  environment = [
    "browser",
    "nodejs"
  ]

[[code_formatters]]
name = "standardjs"